[theme]
theme = "modern"
[theme.overrides]
idle_bg = "#1c1c1c"
idle_fg = "#e4e4e4"
[icons]
icons = "awesome4"

[[block]]
block = "custom"
command = "curl ifconfig.io 2>/dev/null || echo 'no internet access'"
interval = 5
[[block.click]]
button = "left"
cmd = "~/.scripts/vpn-toggle.sh"

[[block]]
block = "custom"
command = "echo -n 'YD:'; yandex-disk status | head -n 1 | cut -d ':' -f 2"
[[block.click]]
button = "left"
cmd = "xdg-open 'https://disk.yandex.ru/client/disk'"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "/usr/bin/pavucontrol"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%R   %a %d %b') "
[[block.click]]
button = "left"
cmd = "xdg-open 'https://calendar.google.com/calendar/u/0/r'"

[[block]]
block = "custom"
command = "~/.scripts/layout.sh"
interval = 1
