[theme]
name = "modern"
[theme.overrides]
idle_bg = "#1c1c1c"
idle_fg = "#e4e4e4"
[icons]
name = "awesome"

[[block]]
block = "custom"
command = "curl ifconfig.io 2>/dev/null || echo 'no internet access'"

[[block]]
block = "custom"
command = "echo -n 'YD:'; yandex-disk status | head -n 1 | cut -d ':' -f 2"
on_click = "xdg-open 'https://disk.yandex.ru/client/disk'"

[[block]]
block = "sound"
on_click = "/usr/bin/pavucontrol"

[[block]]
block = "time"
interval = 60
format = "%R   %a %d %b"
on_click = "xdg-open 'https://calendar.google.com/calendar/u/0/r'"

[[block]]
block = "custom"
command = "~/.scripts/layout.sh"
interval = 1
